#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

echo " Usage: doll <$(ls -1 "$(dirname "$0")" | sed 's/^doll-//g' | tr '\n' '|')>"
