#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

DOLLFILE=${CONF_DIR}/${DOLLFILE}
IGNOREFILE=${CONF_DIR}/${IGNOREFILE}

grep -vf "${IGNOREFILE}" "${DOLLFILE}"
echo --------
grep -f "${IGNOREFILE}" "${DOLLFILE}" | sed 's/^/ignored: /g'
