#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

check() {
	which parallel-ssh
	ssh -oConnectTimeout=10 ${PUPPETUSER}@${PUPPETMASTER} "${SUDO:-} ${PUPPET_PATH:-}puppet master --version"
}

check && echo " All tests passed." || echo " Failed to pass all tests!"
