#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

DOLLFILE=${CONF_DIR}/${DOLLFILE}

do_list() {
	CMD="${SUDO:-} ${PUPPET_PATH:-}puppet cert list --all | grep ^+ | egrep -o '^[^\"]*\"[^\"]*\"' | sed 's/[\+ \"]*//g' | sort -u"
	ssh ${PUPPETUSER}@${PUPPETMASTER} "${CMD}"
}

do_list > "${DOLLFILE}"
