#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

DOLLFILE=${CONF_DIR}/${DOLLFILE}

SORTED=$(cat "${DOLLFILE}" | sort -u)
[ -z "${SORTED}" ] || {
	echo "${SORTED}" > "${DOLLFILE}"
}

doll list
