#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

IGNOREFILE=${CONF_DIR}/${IGNOREFILE}

usage() {
	echo " doll ignore <doll>"
	echo
	echo " put doll on ignore list"
	exit 1
}

[ $# -ne 1 ] && usage

DOLL=$1

echo "${DOLL}" >> "${IGNOREFILE}"
