#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

IGNOREFILE=${CONF_DIR}/${IGNOREFILE}

cat "${IGNOREFILE}"
