#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

DOLLFILE=${CONF_DIR}/${DOLLFILE}

usage() {
	echo " doll filter <pattern>"
	echo
	echo " filter loaded dolls by given pattern"
	exit 1
}

[ $# -ne 1 ] && usage

PATTERN=$1

FILTERED=$(egrep -oE "${PATTERN}" "${DOLLFILE}")

echo "${FILTERED}" > "${DOLLFILE}"

doll list
