#!/bin/bash
set -eu

CONF_DIR="$(cd "$(dirname "$0")/../conf" && pwd)"
CONF_FILE="${CONF_DIR}/doll.cfg"

# shellcheck source=../conf/doll.cfg
source "${CONF_FILE}"

usage() {
	echo " doll add <doll>"
	echo
	echo " add doll to dolls list"
	exit 1
}

[ $# -ne 1 ] && usage

DOLL=$1

echo "${DOLL}" >> "${CONF_DIR}/${DOLLFILE}"
